from authorization.models import *
Auth.objects.create(login='Aswertti', password='q', tel='+79193448376')
Auth.objects.create(login='q', password='q', tel='+78965324245')
Auth.objects.create(login='123', password='123', tel='+78965478522')
Auth.objects.create(login='w', password='w', tel='+79654852142')
Auth.objects.create(body='пошли гулять', otpr_id=2, who_user1='<Auth: Auth object (3)>', who_user2=' <Auth: Auth object (2)>')
Auth.objects.create(body='я не хочу', otpr_id=3, who_user1='<Auth: Auth object (3)>', who_user2=' <Auth: Auth object (2)>')
Auth.objects.create(body='пошли гулять', otpr_id=2, who_user1='<Auth: Auth object (4)>', who_user2=' <Auth: Auth object (2)>')
Auth.objects.create(body='нет, ты меня обидел', otpr_id=4, who_user1='<Auth: Auth object (4)>', who_user2=' <Auth: Auth object (2)>')
Auth.objects.create(body='пошли гулять', otpr_id=2, who_user1='<Auth: Auth object (5)>', who_user2=' <Auth: Auth object (2)>')
Auth.objects.create(body='пошли', otpr_id=5, who_user1='<Auth: Auth object (5)>', who_user2=' <Auth: Auth object (2)>')
